exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.zip"
  - "*.rar"
  - "*.apk"
  - "*.exe"
timezone: Asia/Jakarta
google_analytics: UA-106238155-1
show_downloads: false
