title: "Android Engineer"
baseurl: "/android-engineer" # the subpath of your site, e.g. /blog
url: "https://www.webmanajemen.com" # the base hostname & protocol for your site
github_username: dimaslanjaka
repository: dimaslanjaka/android-engineer
email: dimaslanjaka@gmail.com
author: Dimas Lanjaka
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.zip"
  - "*.rar"
  - "*.apk"
  - "*.exe"
  - "*.img"
  - "*.dll"
  - "*.so"
  - ".vscode/"
  - /script/bootstrap
  - /script/cibuild
  - /script/*.js
  - "**/yarn.lock"
  - "**/package-lock.json"
timezone: Asia/Jakarta
google_analytics: UA-106238155-1
show_downloads: false
logo: https://rawcdn.githack.com/dimaslanjaka/public-source/1a5eb6ac9eec2bd440a694858cdd0f1728e115f1/images/cropped-PicsArt_09-09-12.12.25.jpg

# Permalinks
permalink: /:title
encoding: UTF-8

collections:
  posts:
    output: true
  project:
    output: true

extlinks:
  attributes: { rel: "external nofollow noopener noreferrer", target: _blank }
  rel_exclude: ["webmanajemen.com"]

markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

# enable ES6
jekyll-minifier:
  uglifier_args:
    harmony: true

readme_index:
  enabled: true
  remove_originals: true
  with_frontmatter: true
