title: "Android Engineer"
baseurl: "/android-engineer" # the subpath of your site, e.g. /blog
url: "https://www.webmanajemen.com" # the base hostname & protocol for your site
github_username:  dimaslanjaka
email: dimaslanjaka@gmail.com
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.zip"
  - "*.rar"
  - "*.apk"
  - "*.exe"
timezone: Asia/Jakarta
google_analytics: UA-106238155-1
show_downloads: false
